from FEB2024.own_queue import Queue

def main():
    user_input = int(input('Enter the initial stack size: '))
    que = Queue(user_input)
    print('Is full',que.is_full())
    print('Is empty',que.is_empty())
    print('Top element',que.top_element())
    print('dequeue when empty',que.dequeue())
    que.enqueue(11)
    print(que)
    print(que.size())
    que.enqueue(12)
    print(que)
    print(que.size())
    print('self.top',que.top)
    print('Is Full',que.is_full())
    print('Is empty',que.is_empty())
    result = que.dequeue()
    print('dequeue result',result)
    que.enqueue(13)
    print(que)
    que.enqueue(14)
    print(que)
    que.enqueue(15)
    print(que)
    que.enqueue(16)
    print(que)
    print('top value',que.top)
    que.enqueue(17)
    print(que)
    que.dequeue()
    que.enqueue(17)
    print(que)

if __name__ == '__main__':
    main()
